name: crowd
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.3
  google_fonts: ^3.0.1
  get_storage: ^2.0.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_svg: ^1.1.1+1
  http: ^0.13.4
  get: ^4.6.5
  uuid: ^3.0.6
  pin_code_fields: ^7.4.0
  mongo_dart: ^0.8.0
  intl: ^0.17.0
  geolocator: ^9.0.2
  google_maps_flutter: ^2.2.0
  geocoding: ^2.0.5

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.3
  build_runner: ^2.1.11

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/svg/


